[package]
name = "coordinator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.21"
ic-cdk = "0.13"
ic-cdk-macros = "0.9"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
num-traits = "0.2"
