[package]
name = "refueler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.19"
ic-cdk-macros = "0.19"
candid = "0.10"
serde = { version = "1", features = ["derive"] }
